drop table parser_config if exists;
drop table parser_config_item if exists;
drop table job_config if exists;


/*==============================================================*/
/* Table: parser_config                                         */
/*==============================================================*/
create table parser_config
(
  id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name                 varchar(512) not null,
  type                 integer not null, -- 1.html 2.json
  list_item_selector   varchar(2048) ,
  preview_url          VARCHAR(1024) not null,
  user_agent           VARCHAR(1024),
  referer              VARCHAR(1024),
  timeout              integer,
  remark               varchar(2048) ,
  del_flag             integer DEFAULT 0 not null
);
CREATE INDEX parser_config_name_index ON parser_config (name);
/*==============================================================*/
/* Table: parser_config_item                                    */
/*==============================================================*/
create table parser_config_item
(
  id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parser_config_id     INTEGER not null,
  sub_config_id        INTEGER,
  column_title         varchar(512) not null,
  selector             VARCHAR(2048),
  dom_index            integer not null,
  attribute            VARCHAR(512),
  separator            VARCHAR(32),
  pattern              VARCHAR(512),
  pattern_index        integer,
  item_type            integer not null, --1.dom;2.url;3.page_num
  item_index           INTEGER not null,
  remark               varchar(2048),
  del_flag             integer DEFAULT 0 not null
);

/*==============================================================*/
/* Table: job_config                                            */
/*==============================================================*/
create table job_config
(
  id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_label            varchar(512) not null,
  preview_url          VARCHAR(1024),
  job_params           CLOB(1M),
  job_type             varchar(128) not null,
  parser_id            integer,
  parser_class         varchar(1024),
  sort_result_index    integer, --排序列，从1开始
  remark               varchar(2048),
  del_flag             integer DEFAULT 0 not null
);

CREATE INDEX JOB_CONFIG_JOB_LABEL_index ON JOB_CONFIG (JOB_LABEL);